### PR TITLE
api: rename `is` to `isEqual`

### PR DESCRIPTION
**Pull request by blond**

### CODE REVIEW

**Comment by Guria** [comment]
Api change is not `refactor`

**Comment by blond** [comment]
@Guria changed to `api: rename is to isEqual`, better? :)

**Comment by Guria** [comment]
Better, if not declared following [angular's commit message guideline](https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#type)

**Comment by zxqfox** [comment]
@Guria But wait, what you suggest to use here?

**Comment by Guria** [comment]
Angular commit message guidelines became pretty common. I just noted that there is no `api` type there. I am not insist to strictly follow it. `api` type is ok for me.

**Pull request merged**
