### PR TITLE
Rename `is` to `compare`

### PR DESCRIPTION
**Pull request by Yeti-or**

### CODE REVIEW

**Comment by Yeti-or** [comment]
@zxqfox

**Comment by Yeti-or** [comment]
`isEqual` ?

**Comment by zxqfox** [comment]
Fine for me:
- `BemEntity.is(e1: BemEntity, e2: BemEntity): boolean` — Object.is or...
- `BemEntity.eq(e1: BemEntity, e2: BemEntity): boolean` — https://lodash.com/docs#eq
- `e1.like(e2: BemEntity): boolean` — https://lodash.com/docs#isArrayLike

**Comment by blond** [comment]
> `BemEntity.is(e1: BemEntity, e2: BemEntity): boolean`

It is good for me.

> `BemEntity.eq(e1: BemEntity, e2: BemEntity): boolean`

I don't like too short names.

> `e1.like(e2: BemEntity): boolean`

It's a different logic. Using the `like` method we compare the different types of data. 

Example:

```js
likeNumber(1); // true
likeNumber('1'); // true
likeNumber('a'); // false
```

**Comment by blond** [comment]
I think we should rename instance method to `e1.equal()` or `e1.isEqual()` and add static method `BemEntity.is()`.

**Comment by blond** [comment]
@Yeti-or @zxqfox let's use the `e1.isEqual(e2)`. 

Do you have any objection?

**Comment by zxqfox** [comment]
Fine for me ;-)

**Comment by zxqfox** [comment]
ping @blond

**Comment by blond** [comment]
Closed in favor of #9.

**Pull request closed without merging**
